export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_OK = 'ADD_PRODUCT_OK';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_LOADING_PRODUCTS = 'START_LOADING_PRODUCTS';
export const LOADING_PRODUCTS_OK = 'LOADING_PRODUCTS_OK';
export const LOADING_PRODUCTS_ERROR = 'LOADING_PRODUCTS_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_OK = 'PRODUCT_DELETE_OK';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_PRODUCT_EDIT = 'START_PRODUCT_EDIT';
export const PRODUCT_EDIT_OK = 'PRODUCT_EDIT_OK';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

